/* This file was generated by GiottoC: http://www.eecs.berkeley.edu/~fresco/giotto */

#ifndef _N_TABLE_
#define _N_TABLE_

#include "n_spec.h"

#ifdef DISTRIBUTED
#include "n_code.h"
#endif

#define MAXNETWORK 0  /* max number of networks */

#endif
