/* This file was generated by GiottoC: http://www.eecs.berkeley.edu/~fresco/giotto */

#ifndef _S_TABLE_
#define _S_TABLE_

#include "s_spec.h"
#include "s_code.h"

#define MAXANNOTATION 1  /* max number of annotations */

#endif
