/* This file was generated by GiottoC: http://www.eecs.berkeley.edu/~fresco/giotto */

#include "s_table.h"

annotation_type annotation_table[MAXANNOTATION] = {
  { "giotto_annotation", giotto_schedule_release_code, giotto_schedule_save_release_time_code, giotto_schedule_start_time_code, giotto_schedule_edf_priority }
};

