/* This file was generated by GiottoC: http://www.eecs.berkeley.edu/~fresco/giotto */

#ifndef _F_TABLE_
#define _F_TABLE_

#include "f_spec.h" 
#include "f_code.h"

#define MAXDRIVER    13  /* max number of drivers */
#define MAXCONDITION 5  /* max number of conditions */
#define MAXTASK      2  /* max number of tasks */
#define MAXTRIGGER   1  /* max number of triggers */

#define MAXPORT      10  /* max number of ports */

#endif
