/* This file was generated by GiottoC: http://www.eecs.berkeley.edu/~fresco/giotto */

#ifndef _H_TABLE_
#define _H_TABLE_

#include "h_spec.h"

#ifdef DISTRIBUTED
#include "h_code.h"
#endif

#define MAXHOST 0  /* max number of hosts */

#endif
