/* This file was generated by GiottoC: http://www.eecs.berkeley.edu/~fresco/giotto */

#ifndef _E_CODE_
#define _E_CODE_

#include "e_spec.h"

#define NPROGRAM      150
#define MAXPROGRAM    300
#define MAXSCHEDULE   10
#define MSEC_PER_UNIT 50

#endif
